### PR TITLE
[OPTIONAL] chore(prettier): Adds prettier for code formatting consistency 

### PR DESCRIPTION
**Pull request by sad-squid**
Totally optional, just noticed the code was a little hard to read in some places because it was quite inconsistent w/ spacing, formatting, etc.

- Added [prettier](https://prettier.io/) to help code format and cleans everything up a bit. All changes should be formatting changes, with the exception of the new dev packages added to `package.json` and `yarn.lock`. 
- Updated eslint config to allow for prettier as a code formatter
- Updated eslint config to specify version of react (previously was showing warning when running lint)
- Ran prettier with `yarn prettier write .` to format all files automagically . 
- Removed unnecessary eslint rules since prettier was added. 

If this change is accepted, I can add hooks to make it auto-run pre-commit or add something in the README to include more details.

### CODE REVIEW

**Comment by ottomated** [comment]
merging but I use tabs :)

**Comment by sad-squid** [comment]
@ottomated Should I update the prettier config for tabs instead of spaces? Wondering why the branch is closed instead of merged

**Comment by OiYouYeahYou** [comment]
@sad-squid probably because they merged it locally and closed it to keep track of what work needs to happen

**Comment by sad-squid** [comment]
Gotcha... Was confused cuz it wasn't mentioned. Thanks for clarification @OiYouYeahYou - I'll leave my new PR up in case and if it's a duplicate we can just close it later.

**Pull request closed without merging**
