### PR TITLE
- Support for X64 version of the game (Epic , WIP)

### PR DESCRIPTION
**Pull request by OhMyGuus**
This PR will fix the following things: 
- Support for Windows store & epic store (x64 version of the game) ( issue: #411 )
- Having to update the server on every small update
- New method of getting the gamecode which will work when you're in the middle of  the game. 

- Tested working game versions: 
   - Steam version (12.9 & 12.5)
   - Windows store version
   - Epic store version
   - Cracked version I found on the internet

   
_-- note --_ 
If you want to test the PR you can try my fork of Crewlink: https://github.com/OhMyGuus/BetterCrewLink

### CODE REVIEW

**Comment by realwakils** [comment]
Does the 'New method of getting the gamecode which will work when you're in the middle of the game.' involve grabbing the pointers from GameAssembly.dll?

**Comment by OhMyGuus** [comment]
> Does the 'New method of getting the gamecode which will work when you're in the middle of the game.' involve grabbing the pointers from GameAssembly.dll?

Yes it does but it is one less pointer than before, 
crewlink used to do this: 
GameStartManager -> GameRoomName -> Text
Which was anoying since GamestartManager is in a destroyableSignalton which is harder to sig and GameStartManager was only avaible when you where actually in the "lobby".

Now I changed it to: 
InnerNetClient -> GameId
This makes it way cleaner because this is the actual way the game stores the lobby code and we where already using InnerNetClient for the gamestate. As well since this class has a normal static instance it makes it way simpler to sigscan and so to auto update.

**Comment by DispatchCommit** [comment]
> this class is always available as well so when someone didn't start Crewlink in time or needs to restart it in the middle of the game Crewlink still is able to get the gamecode from the game.

Oh that would be such a nice quality of life improvement! And sounds like a much nicer approach as well.

> we don't need to change anything when the game updates and we don't have to get the offsets manually for 10 versions of the game.

That's an even bigger selling point IMO. This sounds great overall

**Comment by OhMyGuus** [comment]
For the people who wants to test it and give feedback I just released a test version to my fork: 
https://github.com/OhMyGuus/CrewLink/releases

**Comment by DispatchCommit** [comment]
I'm working on merging some of the network enhance / improvements improvements into my fork of overlays + lobby specific settings, Since many of the benefits I see to this PR being the flexibility to accommodate and adapt to future releases, I think I may end up pulling this in as well since it offers so many advantages.

Are there any good resources for learning about how the offsets are found?

**Comment by DorCoMaNdO** [comment]
A little off topic but could you perhaps add signatures for a few more offsets used by this fork (probably not in this PR) https://github.com/pau101/CrewLink https://github.com/pau101/CrewLink-server (and my fork which is based on that one), they're used to enable additional features such as hearing people through cameras, disabling voice during comms sabotage (a way to tell the state of other emergencies too would be appreciated), getting the current map and which doors are open/closed.

**Comment by OhMyGuus** [comment]
> A little off topic but could you perhaps add signatures for a few more offsets used by this fork (probably not in this PR) https://github.com/pau101/CrewLink https://github.com/pau101/CrewLink-server (and my fork which is based on that one), they're used to enable additional features such as hearing people through cameras, disabling voice during comms sabotage (a way to tell the state of other emergencies too would be appreciated), getting the current map and which doors are open/closed.
Problem is that there are no Pull request for those features so I don't think that will be in the offical ever. I added the clientid, hostid tho because there are 2 other pull request in here that uses those variables.

**Comment by OhMyGuus** [comment]
This PR only needs a fix for the OpenGame Function which now just starts the steam game.
I'm still thinking for the best solution to detect which game version is installed, if someone here has a good idea to solve this or already solved this problem be my guest and help me out!

**Comment by DorCoMaNdO** [comment]
> Problem is that there are no Pull request for those features

Those are commonly requested features and some of them are planned by @ottomated (see #7 for comms sabotage), there are other forks working on different implementations for stuff like wall muffling but they all depend on knowing information such as what map is being played, what camera is being viewed, the state of an emergency (mostly comms sabotage), the state of doors (open/closed, affecting voice muffling).
But for any fork (and eventually this main repo) to have this information reliably, we'd need to depend on patterns instead of direct offsets for the same reason this PR exists.

**Comment by ottomated** [comment]
So you're telling me that with this, offsets are the same for each version of the game? Independent of future updates and platforms?

**Comment by OhMyGuus** [comment]
> So you're telling me that with this, offsets are the same for each version of the game? Independent of future updates and platforms?

Yes, you don't have to change a thing made a mistake tho in the offsets.yml

> So you're telling me that with this, offsets are the same for each version of the game? Independent of future updates and platforms?
Yes only when they do a super big change like when they make big changes to the compiler settings to or change the obfuscator it will break but that doesn't happen often (or basically never) 
Made a small update btw in the offsets.yml to support more versions of the game bcs there was still a small mistake in it so be aware of it (its in the same branch as last time)

**Comment by OhMyGuus** [comment]
PR is done and tested now btw, only thing is that button but you can handle that with a message I guess.

**Comment by GKwok88** [comment]
Sorry for sounding a bit dense but am I right in assuming that this is would make the chat mod usable for the game bought on Epic Games? I don't have Among US on Steam unfortunately!

**Comment by OhMyGuus** [comment]
> Sorry for sounding a bit dense but am I right in assuming that this is would make the chat mod usable for the game bought on Epic Games? I don't have Among US on Steam unfortunately!

Yes, this would make it work for Epic, Windows store, itch.io

**Comment by TheSpringBoy** [comment]
This PR actually fixes my problem.
( #467 )

**Comment by GKwok88** [comment]
> > Sorry for sounding a bit dense but am I right in assuming that this is would make the chat mod usable for the game bought on Epic Games? I don't have Among US on Steam unfortunately!
> 
> Yes, this would make it work for Epic, Windows store, itch.io

Great! Thanks for your hard work in this! Looking forward to it!

**Comment by ian-cammy** [comment]
BetterCrewLink v1.2.14 works great with Microsoft Store release.

**Pull request merged**
