### PR TITLE
Muffling vents

### PR DESCRIPTION
**Pull request by bluo999**
Here from https://github.com/ottomated/CrewLink/issues/133. Added a low pass filter when inside a vent. Gain is lowered as the audio isn't bearable at max when using the filter.

Implements https://github.com/ottomated/CrewLink/issues/24.

### CODE REVIEW

**Comment by hooplapunta** [comment]
We'll be uploading a video to show that it works in a little bit

**Comment by hooplapunta** [comment]
For your convenience in review, please check out the link for a video showing this enhancement in action.

https://user-images.githubusercontent.com/10163238/102907890-a26ec280-44b1-11eb-894d-c028daa908af.mp4

**Comment by pederjohnsen** [comment]
How does the person in the vent sound to the people outside of the vent?

**Comment by realwakils** [comment]
> How does the person in the vent sound to the people outside of the vent?

The person in the vent is muted.

**Pull request merged**
