### PR TITLE
Add In-Game Overlay

### PR DESCRIPTION
**Pull request by Ornamus**
An implementation of #13 ready to go. This overlay is Discord-style rather than placing the talking icons over the player's heads, though there's room to implement/combine this with the talking icons down the road.

This uses `electron-overlay-window` to create an Electron BrowserWindow that sits invisibly over an application of choice, and will follow it/resize to match it. Because of this, the entire overlay can be made using React still, so some existing components and code can be reused.

The overlay can be displayed either on the top-center of the screen, or moved to the bottom-left corner. By default, all connected users are shown in the lobby and during meetings, and appear when talking when in game (a-la Discord). For those who want it to be less prominent, a compact mode can be enabled that makes it so that it _only_ shows anyone, regardless of game state, if they're talking.

I highly suggest pulling this branch and playing around with it to get the full feeling, but here's a couple static screenshots (check the left side / top). 

_(visuals as of 12/10/2020)_
new_overlay1
_Unobtrusive indicator that the overlay has loaded and connected_

new_overlay2
_When in a lobby or meeting with compact mode off, you can see all players_

new_overlay3
_When in the tasks phase, or when compact mode* is on, players only appear if talking_

_*compact mode additionally removes names, not pictured in this screenshot_

I'm entirely open to feedback, adjustments, and requests ;)

### CODE REVIEW

**Comment by leny32** [comment]
A few suggestions:
- When on the main screen etc. (outside lobby and in-game), move it a little down below the version name.
- Positioned in the bottom left or top center, as there isn't much interaction there from before.
- Only appears once in the lobby.
- Have a compacted mode that can be toggled, which removes the names and non-speaking users.

**Comment by Ornamus** [comment]
Thanks for the suggestions! I agree with pretty much all of it, I'll get working on them alongside the polishing.

**Comment by ottomated** [comment]
Very cool PR, only question is the fullscreen compatibility. Have you tested that?

**Comment by Ornamus** [comment]
> Very cool PR, only question is the fullscreen compatibility. Have you tested that?

Yup, it works perfectly fine in fullscreen!

**Comment by OiYouYeahYou** [comment]
Just jumped into a public lobby with someone, and there's some encoding problems it seems

image

**Comment by OiYouYeahYou** [comment]
Just jumped into a public game and it seems there's some encoding issues

unknown2
unknown3

**Comment by Ornamus** [comment]
> Just jumped into a public game and it seems there's some encoding issues
Indeed! But that's not an issue directly with the game overlay, CrewLink in general has those encoding issues.
image

**Comment by bmoe24x** [comment]
Just wanted to say @ottomated this app is insane for a 17 year old. Amazing level of ingenuity and dedication, nice work 🤘 some of these PRs are really cool too

**Comment by realwakils** [comment]
Hey @Ornamus I'm getting 'Cannot find module 'electron-overlay-window' or its corresponding type declarations.' when I tried your code.
Any idea why? Sorry if it's obvious :).
image

**Comment by Ornamus** [comment]
> Hey @Ornamus I'm getting 'Cannot find module 'electron-overlay-window' or its corresponding type declarations.' when I tried your code.
> Any idea why? Sorry if it's obvious :).
> image
> 

You just need to run `yarn install` 
again to install the additional packages this PR uses!

**Comment by realwakils** [comment]
Great that worked!

**Comment by OiYouYeahYou** [comment]
Minor issue: There are a few eslint errors on the changes you've added. Things like nested function declarations and missing semis. If you fix them now, it'll be less stuff to fix in the future :)

**Comment by leomelki** [comment]
Maybe adding an option to put the overlay at top or left of the screen would be great

**Comment by OiYouYeahYou** [comment]
> Maybe adding an option to put the overlay at top or left of the screen would be great 👌.

Actually, this could be really useful if it covered up the server code for streamers

**Comment by jydmnd** [comment]
@ottomated Why was the compact mode and top placement removed in commit 2f3fec1 ?

**Comment by ottomated** [comment]
I had to rewrite this commit from scratch because it didn't match the code style

**Pull request merged**
