### PR TITLE
Better error messages for invalid or unsupported servers

### PR DESCRIPTION
**Pull request by tystuyfzand**
This rewrites the error messages given when fetching version files to confirm that:

- The server responds to a request to `/health`
- The response is JSON
- The server lists the game version in the supported versions

If any of the following happen, it will return a more helpful error message:

- The server returns a 404 for the health check (Likely an invalid server url)
- The server responds with a 500-504 error (standard http errors for reverse proxies/service errors)
- The server responds with a 520-524 error (Cloudflare error codes for origins)
- The connection times out (Server is offline or not reachable)
- The connection is refused (The server responds, but instantly denies the connection due to a firewall/etc)

This makes it more clear what's going on, and hopefully lessens the amount of people asking for help when the main server/etc are down.

The downside of this is that certain servers (I see The Skeld on the uptime list) do not support this, but it's a simple enough fix.

### CODE REVIEW

**Comment by ottomated** [comment]
Will not merge because of the huge amount of load this will cause, but something similar will work

**Comment by ottomated** [comment]
Also the messages need to be dumbed down *significantly*

**Comment by tystuyfzand** [comment]
@ottomated Agreed that they need to be dumbed down, I'm a developer at heart so I have trouble with that sometimes 😓 

Shouldn't cause any load at all, it'd be about the same as getting a file from the server. The way the `/health` endpoint is written, it uses either existing data, or very cheap method calls to return anything. See [this block of code](https://github.com/ottomated/CrewLink-server/blob/master/src/index.ts#L51-L59) - it's rendering a json response instead of a file from the filesystem, so if anything it's less load since it doesn't have file IO involved.

Overall, the index route would in theory cause more load as it renders a template, and even then this is called only once and cached on the client when the offsets don't exist, not even guaranteed to be called every server switch.

**Comment by tystuyfzand** [comment]
This isn't relevant anymore with the game versions being embedded and upcoming plans to redo messages. Closing.

**Pull request closed without merging**
