### PR TITLE
added intuitive refresh button

### PR DESCRIPTION
**Pull request by realwakils**
Someone else suggested a refresh button but it wasn't correctly placed. This one will stick right next to the settings icon. I've also matched the colors. One thing to change would be the thickness of the refresh icon. I think it's too thin. Details though details.
image

### CODE REVIEW

**Comment by notexplosive** [comment]
Hi! I made the [PR for the other Refresh button](https://github.com/ottomated/CrewLink/pull/399).

My main concern is the button is too small. From your screenshot I measure 24x24 pixels on normal DPI. I realize that it's the same story for the settings button, but I change my settings way less often then I refresh.

At the end of the day, I'm good with either, just offering my two cents.

**Comment by realwakils** [comment]
Yeah that's fair. For me personally I prefer a smaller not as in-your-face button, but I understand your concerns.
Might be a dumb idea, but perhaps an option in the settings menu to toggle between the two refresh buttons.

Might be too much though just throwing that out there.

**Comment by Becold** [comment]
I would add a tooltip with : `Restart the application (CTRL+R).`
But that's fine for me.

**Comment by realwakils** [comment]
There you go @Becold. I added a little tool tip now. Also a little scale up animation.

**Comment by OhMyGuus** [comment]
What commits are now in this PR? since I see like 8 commits from other pull request that are not merged into master..?
Maybe just an idea for next time make an feature branch only for the feature and use that for the PR, because I don't see this being merged anytime soon if it has other pull request in it as well.

**Comment by realwakils** [comment]
> What commits are now in this PR? since I see like 8 commits from other pull request that are not merged into master..?
> Maybe just an idea for next time make an feature branch only for the feature and use that for the PR, because I don't see this being merged anytime soon if it has other pull request in it as well.

None other commits are here then the refresh button. The other pull requests I included was by accident (i'm a bit new to git). I have reverted all those commits.

**Comment by stevebell117** [comment]
> 
> 
> > What commits are now in this PR? since I see like 8 commits from other pull request that are not merged into master..?
> > Maybe just an idea for next time make an feature branch only for the feature and use that for the PR, because I don't see this being merged anytime soon if it has other pull request in it as well.
> 
> None other commits are here then the refresh button. The other pull requests I included was by accident (i'm a bit new to git). I have reverted all those commits.

Unfortunately you're including changes from #391 still. Also, your package-lock.json file change is huge, is that expected? I don't see why 12.5k lines would be added for what you're doing.

**Pull request closed without merging**
