### PR TITLE
added microphone test and speaker test to settings menu

### PR DESCRIPTION
**Pull request by ItzDerock**

### CODE REVIEW

**Comment by ItzDerock** [comment]
build failed due to a 503 when downloading a dependency.

`gyp ERR! stack Error: 503 response downloading https://electronjs.org/headers/v9.3.3/node-v9.3.3-headers.tar.gz`

shouldn't cause an issue if you've already got the dependencies.

**Comment by ottomated** [comment]
A couple things: can you embed the test audio file, and can you use React principles?

**Comment by ItzDerock** [comment]
> A couple things: can you embed the test audio file, and can you use React principles?

I can embed the audio file, as for using react principles, I don't have a lot of experience with react, so I'll need a little help for that.

**Comment by ItzDerock** [comment]
just saw pr 90 (https://github.com/ottomated/CrewLink/pull/90), does what I added, closing this now.

**Pull request closed without merging**
