### PR TITLE
Add "Haunting" of Impostors

### PR DESCRIPTION
**Pull request by Ornamus**
This does half of issue #25: ghosts are able to (faintly) talk to nearby living impostors. The ghost's max audio is significantly reduced to hopefully prevent them from interfering too much with living conversations, and additionally have a reverb affect applied to them to make them sound more... "ethereal". 

Ghosts can't be heard during meetings still, and if a particular player finds the feature frustrating they can disable it for themselves in the settings.

image

### CODE REVIEW

**Comment by ottomated** [comment]
Cool. This relies on #7 now.

**Comment by sjoerd108** [comment]
Maybe offload the impulseResponse to a separate .bin file and use a node buffer to load it in. Im not an audio expert but what exactly is the large binary blob for?

**Comment by ottomated** [comment]
This will increase CPU usage significantly, I'm going to ask that you make it so the additional audio nodes are only loaded when necessary.

**Comment by Ornamus** [comment]
@sjoerd108 Fair enough, I'll get on moving it to a separate file. The blob is an AudioBuffer that dictates what sort of effect you get from the ConvolverNode.

@ottomated On it. How would you like me to approach that? I haven't worked a ton with these Audio Nodes before - should I just disconnect them until needed, connect them, then disconnect again? Or only instantiate them when needed, then promptly destroy the objects entirely?

**Comment by ottomated** [comment]
I would only connect them when the setting option is true

**Comment by bnb** [comment]
YES PLEASE GOD YES

**Comment by Ornamus** [comment]
Implemented the requested changes! The reverb effect is now stored in `reverb.ogx` in the static folder, and the reverb audio nodes aren't created or connected unless haunting is enabled.

**Pull request merged**
