### PR TITLE
Replace on-the-fly player image generation with static images

### LINKED ISSUE #11: Robotic audio when people join lobby, change cosmetics, change from alive to dead
This is likely due to excess CPU usage in https://github.com/ottomated/CrewLink/blob/master/src/renderer/Avatar.tsx when loading images.

### PR DESCRIPTION
**Pull request by vrnagy**
The images was generated with the same logic as before. This modification solves the CPU spike on lobby joins and fixes #11
We tested it for the last 2 days withouth any error.

### CODE REVIEW

**Comment by leny32** [comment]
Wouldn't it be better to grayscale the `colorAlive` and put an X-mark on top of it, when they're dead instead of doing another 12 images? Just an opinion.

**Comment by vrnagy** [comment]
The main point in this PR was to maintain the current behavior with significant performance improvement

**Comment by TheSpringBoy** [comment]
> The main point in this PR was to maintain the current behavior with significant performance improvement

You forgot all the hats and accessories.....

**Comment by vrnagy** [comment]
> > The main point in this PR was to maintain the current behavior with significant performance improvement
> 
> You forgot all the hats and accessories.....

The functionality of hats and skins are not changed at all. (See the attached image, the second player was on mobile) If You check the code, You can see only the color changing code was removed, which caused the CPU spikes earlier.

image

**Comment by TheSpringBoy** [comment]
ohh
so youre saying that only the color changing was the problem?
and not the hats?
so your idea is pretty cool

**Comment by vrnagy** [comment]
Yes because every pixel of the base image had to be recolored with color calculation in the background, which is an expensive operation. We tested it with about 20 different people and the lags on lobby join were gone. If we want to it more, it can be done with CSS positions only bot it would be a little tricky to get done

**Comment by OiYouYeahYou** [comment]
This solves the problem of audio glitches when people spam cosmetic changes?

**Comment by vrnagy** [comment]
Yes

**Pull request merged**
