### PR TITLE
Updated README on how to fix application volume issues.

### PR DESCRIPTION
**Pull request by JavanPoirier**
On Windows, if you have your sound communications settings set to reduce volume upon joining a call, the CrewLink application volume will be impacted by this when anyone joins/leaves the lobby. To fix this go to your Sound settings through the Control Panel and set it to "Do nothing".

This did not seem to be fixable from an application perspective, at least not easily. I looked into application volume control, however all the packages available seem to only be able to control system master volume. The underlying solution is not to adjust the application volume, but instead to not have windows pick it up as a "call". However, I am not sure if that is something easily changeable and may just be an OS thing with RTC.

Lastly, I put the jpeg in the resources folder, which means it will be included in the build which may not be ideal. I was thinking about having this in a popup on first time startup, but didn't.

EDIT: Maybe a FAQ instead of Known Issues may be better.

### CODE REVIEW

**Comment by ottomated** [comment]
This is a workaround. Not merging.

**Comment by JavanPoirier** [comment]
So you would rather have people not know about to address this? As mentioned above, an actual solution for this may not even be possible as it may be determined by the OS. I think it is huge oversight to just let this slip and provide no information to users about this. In the group of 10 I played with, at least 3 others had this issue.

**Comment by ottomated** [comment]
Yes

**Comment by nitro404** [comment]
@ottomated Multiple people I play with had this issue as well, but did not realize what the cause was and had a lot of difficulty hearing each other. I think this is valuable information to include as part of the setup process since it is not a workaround, but rather a recommendation for the best practice when using communication software on a Windows computer. It doesn't hurt anything.

**Pull request closed without merging**
