### PR TITLE
Add mute key (RAlt).

### PR DESCRIPTION
**Pull request by DorCoMaNdO**
Adds mute key support, bound by default to RAlt, a different icon is added too, licensed under MIT, separate commits so you could cherry pick.

### CODE REVIEW

**Comment by DispatchCommit** [comment]
I PR'd this to my fork for testing and initial feedback is just that users can be *both* deafened *and* muted, but the deafened icon will overlap the mute icon. I suppose that isn't an actual issue since un-deafening will then show as being muted still, but just an observation. 

A potential simple solution to this would be making it so that toggling mute automatically un-deafens, however toggling deafen should *not* automatically unmute. In this way the behavior would be similar to discord's muting / deafening.

**Comment by DorCoMaNdO** [comment]
Yeah you're right that undoing mute should automatically undeafen, I'll fix that when I'm done reworking my settings implementation.
The deafen icon overrides the mute icon since deafen implies mute.

**Comment by ottomated** [comment]
I intentionally did not include this feature because it is redundant through the existence of deafen and push-to-talk.

**Comment by DispatchCommit** [comment]
> Yeah you're right that undoing mute should automatically undeafen, I'll fix that when I'm done reworking my settings implementation.

Sounds good, I'll be keeping an eye out for that so I can pull that into my fork as well, though with the update that just came out today I'm stuck on waiting for the updated memory offsets before I can do much more testing with other players.

**Comment by DorCoMaNdO** [comment]
> I intentionally did not include this feature because it is redundant through the existence of deafen and push-to-talk.

There are valid reasons to want to mute without deafening, and without switching to push to talk, lots of people to transmit all the time when it's related to the game, but there are certain times you'd want to mute but still hear what others say, like when you need to talk to someone irl, or for streamers, to reply to chat/donations/etc.

**Comment by ottomated** [comment]
I think that all of the situations you described are more suited to deafening over muting.

**Comment by DorCoMaNdO** [comment]
Streamers I'm watching would beg to differ, they might be dead in game so they can talk to the chat, but they don't want to be deafened if someone in-game wants to talk to them. Streamers seek time to talk to chat during their games, but that doesn't mean they want to completely disconnect from whatever's going on in the game by deafening.

**Comment by DJ1ce** [comment]
Would be nice to expand this a bit and add a Whisper button feature that allows you to talk with someone that is very close without others hearing. Even better if the people within normal hearing range, but not close enough to hear the whisper would hear a whispering sound so they know people are whispering, but can't hear what is being said.

**Comment by ryantheleach** [comment]
@DJ1ce That is way outside the scope of this pull request, and would be suited to it's own issue.

**Comment by DJ1ce** [comment]
> @DJ1ce That is way outside the scope of this pull request, and would be suited to it's own issue for discussion.

Removed it from here and added it as an issue. Thanks!

**Pull request merged**
